### ISSUE TITLE
quadratic function

### ISSUE THREAD

**Issue by lzblack** [SmitPatel19/MIS3615-COURSE#1]
Well your code definitely works, but it is not a function.

**Comment by SmitPatel19** [comment]
Ya sorry professor, I didn’t want to bother you late night, and was hoping
we can go over it today in class. I spent some time on it and tried a lot
of methods but ultimately turned to the internet for help, I hope that was
okay? And I didn’t just copy and paste, I spent the time to try and
understand the best what’s going on
